CLIENT_ID=![L6BEb4kKor1FCXNoOckYfN5RCUW1jLK87Vf9k9WA21jV/VFvub24jg==]
CLIENT_SECRET=![kZh+GxvrGBoMqXU5TDsclnG1DyxOMzfm9HrVv0/oWGDMbxtA0uvFAg==]
ENV_CLIENT_ID=![LR3505e6/QGzvLuoAISVU1okA5izgjV/R0vxAm47HW7F4Bf6IfEiLg==]
ENV_CLIENT_SECRET=![cIvRybJQNAvQzl+i1jt/VjxJMLsYeOZuCIrYhYokY8EIC0cBsih+5A==]
ORG_ID=6d20974e-34c3-4c3e-98a0-390e788adff0
ENV_NAME=Sandbox
TARGET_ID=cloudhub-us-east-2
APP_NAME=anypoint-cicd-complete-new-demo-design
RUNTIME_VERSION=4.11.2
APP_ASSET_ID=anypoint-cicd-complete
APP_ASSET_VERSION=1.0.0
SPEC_ASSET_ID=cicd-test
SPEC_VERSION=1.0.0